INSERT INTO `user` (`id`, `subject`, `password`, `pwdChangeDate`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `username`, `nickname`, `description`, `roleId`, `orgId`)
VALUES (1, 'admin', '$2a$10$0rW2vfi9qPY.uFWeEmxv3eGrq7UpAWTvNoaStJrogN6qSLid2d/oe', '2023-12-31', 1, '2023-01-01 00:00:00', 'super-admin', '2023-01-01 00:00:00', 'super-admin', 0, '超级管理员', '超管', '', 1, 1);



INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (1, 0, 'OrganizationService', 'OrganizationService', '组织模块', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (2, 1, 'organization', 'OrganizationService🌟organization', '组织管理', 2, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (3, 1, 'user', 'OrganizationService🌟user', '用户管理', 2, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (4, 1, 'role', 'OrganizationService🌟role', '角色管理', 2, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (5, 1, 'permission', 'OrganizationService🌟permission', '权限管理', 2, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (6, 1, 'dictionary', 'OrganizationService🌟dictionary', '数据字典', 2, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (7, 2, 'organization:query', 'OrganizationService🌟organization🌟organization:query', '组织管理-查询', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (8, 2, 'organization:save', 'OrganizationService🌟organization🌟organization:save', '组织管理-保存', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (9, 2, 'organization:delete', 'OrganizationService🌟organization🌟organization:delete', '组织管理-删除', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (10, 3, 'user:query', 'OrganizationService🌟user🌟user:query', '用户管理-查询', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (11, 3, 'user:save', 'OrganizationService🌟user🌟user:save', '用户管理-保存', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (12, 3, 'user:delete', 'OrganizationService🌟user🌟user:delete', '用户管理-删除', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (13, 4, 'role:query', 'OrganizationService🌟role🌟role:query', '角色管理-查询', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (14, 4, 'role:save', 'OrganizationService🌟role🌟role:save', '角色管理-保存', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (15, 4, 'role:grant', 'OrganizationService🌟role🌟role:grant', '角色管理-授权', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (16, 4, 'role:delete', 'OrganizationService🌟role🌟role:delete', '角色管理-删除', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (17, 5, 'permission:query', 'OrganizationService🌟permission🌟permission:query', '权限管理-查询', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (18, 5, 'permission:save', 'OrganizationService🌟permission🌟permission:save', '权限管理-保存', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (19, 5, 'permission:delete', 'OrganizationService🌟permission🌟permission:delete', '权限管理-删除', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (20, 6, 'dictionary:query', 'OrganizationService🌟dictionary🌟dictionary:query', '数据字典-查询', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (21, 6, 'dictionary:save', 'OrganizationService🌟dictionary🌟dictionary:save', '数据字典-保存', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (22, 6, 'dictionary:delete', 'OrganizationService🌟dictionary🌟dictionary:delete', '数据字典-删除', 3, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (23, 0, 'StoreMarkerService', 'StoreMarkerService', '库存模块', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (24, 0, 'PurchaseService', 'PurchaseService', '采购模块', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (25, 0, 'TransportService', 'TransportService', '运输模块', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `permission` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (26, 0, 'FinanceService', 'FinanceService', '财务模块', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);



INSERT INTO `role` (`id`, `code`, `name`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (1, 'system', '系统管理员', 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);



INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (1, 0, 'one', 'one', '公司董事会', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (2, 1, 'two', 'one🌟two', '公司总经理', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, '总经理办公室', NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (3, 2, 'three-1', 'one🌟two🌟three-1', '人力资源部', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (4, 2, 'three-2', 'one🌟two🌟three-2', '财务部', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (5, 2, 'three-3', 'one🌟two🌟three-3', '物流部', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (6, 2, 'three-4', 'one🌟two🌟three-4', '信息部', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (7, 2, 'three-5', 'one🌟two🌟three-5', '市场部', 1, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (8, 0, 'three-6', 'three-6', '上海分公司', 4, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);
INSERT INTO `organization` (`id`, `pid`, `code`, `pCode`, `name`, `type`, `sort`, `leaf`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`, `functionalAuthority`, `workingProcedure`, `relatedRequirement`) VALUES (9, 0, 'three-7', 'three-7', '北京分公司', 4, 0, 0, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL, NULL, NULL, NULL);



INSERT INTO `dictionary` (`id`, `code`, `name`, `value`, `type`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (1, 'OrganizationType', '组织架构类型', NULL, 2, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `dictionary` (`id`, `code`, `name`, `value`, `type`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (2, 'UserGender', '性别', NULL, 2, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `dictionary` (`id`, `code`, `name`, `value`, `type`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (3, 'PermissionType', '权限类型', NULL, 2, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `dictionary` (`id`, `code`, `name`, `value`, `type`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (4, 'DictionaryType', '数据字典类型', NULL, 2, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `dictionary` (`id`, `code`, `name`, `value`, `type`, `enabled`, `createdDate`, `createdBy`, `lastModifiedDate`, `lastModifiedBy`, `version`, `description`) VALUES (5, 'Enabled', '状态', NULL, 2, 1, '2023-01-01 00:00:00', 'supper-admin', '2023-01-01 00:00:00', 'supper-admin', 0, NULL);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (1, 1, '1', '直线制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (2, 1, '2', '职能制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (3, 1, '3', '直线－职能制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (4, 1, '4', '事业部制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (5, 1, '5', '模拟分权制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (6, 1, '6', '矩阵制', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (7, 1, '7', '扁平式', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (8, 2, '1', '男', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (9, 2, '2', '女', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (10, 3, '1', '模块', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (11, 3, '2', '菜单', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (12, 3, '3', '功能', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (13, 4, '1', '参数（单值）', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (14, 4, '2', '映射（多值）', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (15, 5, 'true', '启用', 0);
INSERT INTO `dictionaryItem` (`id`, `dictId`, `code`, `value`, `sort`) VALUES (16, 5, 'false', '停用', 0);
