server:
  port: 7400
  servlet:
    context-path: /

logging:
  level:
    com.kapok.erp.organization: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7200/eureka

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/kapok_org?allowMultiQueries=true&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: kapok_org
    password: "{cipher}3a16193671a38d0e8f80e64d9e2da3d6d590d9f1c780ce43b192015e08353b08355c1e76229428c976d3c5cb3a43457f"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 3
      max-wait: 6000
      min-idle: 3
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    locale: zh_CN
    time-zone: Asia/Shanghai
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      fail-on-empty-beans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7000/oauth2/jwks


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,refresh
